# Generated by Django 5.2.14 on 2026-06-01 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('completed', models.BooleanField(blank=True, default=False)),
                ('added_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
